### PR TITLE
Total rewrite

### PR DESCRIPTION
**Pull request by ghost**
This is a complete rewrite of the `astro` library in order to support the planets and stars (in addition to the luminaries, that were already supported). In so doing, it seemed like a reasonable time to rewrite the entire interface.

This is not yet complete:

* [x] Tests need to be written to verify the accuracy and correctness of everything!
    * [x] sun
    * [x] moon
    * [x] planets
    * [x] fixed stars
* [x] The moon's position is (theoretically) inaccurate, since it's close enough that your position on the surface of the earth matters. We need to apply a correction factor when you go into horizontal coordinates.
* [x] The moon should include phase, illuminated fraction, etc.
* [ ] Rise/set/transit times should be supported.
* [x] I just picked a few bright and culturally/historically important stars. Should we add other things, too?
* [x] There's a lot of room for optimization. (One thing I'm particularly curious of: I'm using `defineGetter` to set cached objects on the local object. This is elegant and convenient, but is a different method more efficient?)

### CODE REVIEW

**Comment by ironwallaby** [comment]
I tested `defineProperty` and it's quite slow. I'll switch to other ways of doing it.

**Comment by YOEL311** [comment]
when will it be ready
Can I help with something?

**Comment by ironwallaby** [comment]
It'll be ready when it's ready :)

It's just waiting on time to finish up the rise/transit/set portions. The math isn't hard, I've just been really busy for the last two weeks, and expect to be really busy for the next few.

**Comment by ironwallaby** [comment]
I rewrote all of this again, for more accuracy and to support sunrise and set. Will open a new PR.

**Pull request closed without merging**
